### ISSUE TITLE
Template of markdown/literate doc file to add new changes to STAGING?

### ISSUE THREAD

**Issue by tonyliang19** [CommunityUBC/ubcwiki#12]
Hello, I'm wondering is there any or possibly could exist a template `md` or any kinds of literate file, so new users that are willing to provide updates could use that. It is good that the file could have:
- Right syntax that is standard to other docs on the wiki now
- Optional or Required css tags

**Comment by CommunityUBC** [comment]
Hello, thank you for waiting

We have added instructions and a boilerplate here: https://ubcwiki.ca/meta/project.html#want-to-add-a-new-page
