### ISSUE TITLE
Fix weird render on bad links, should go to 404

### ISSUE THREAD

**Issue by CommunityUBC** [CommunityUBC/ubcwiki#24]
Works locally, but fails in prod

Potential useful threads:
- https://github.com/squidfunk/mkdocs-material/issues/853
- https://github.com/mkdocs/mkdocs/issues/1598
- https://github.com/papermoonio/moonbeam-mkdocs/pull/3

**Comment by melwee01** [comment]
Can confirm that this happens on our site too for subpages (domain/page/subpage.html level), and only in production or static builds. Top-level pages don't throw a 404 either, but kick back to index.html. In dev, all of these would go to a 404 page.

In the case of dev, the stylesheet is loaded during the build from /assets/stylesheets, but prod is using asset/stylesheets and not finding the 404 for pages that aren't in the same subdirectory. We're not sure how to fix this.

**Comment by CommunityUBC** [comment]
> Can confirm that this happens on our site too for subpages (domain/page/subpage.html level), and only in production or static builds. Top-level pages don't throw a 404 either, but kick back to index.html. In dev, all of these would go to a 404 page.
> 
> In the case of dev, the stylesheet is loaded during the build from /assets/stylesheets, but prod is using asset/stylesheets and not finding the 404 for pages that aren't in the same subdirectory. We're not sure how to fix this.

We were actually able to resolve this issue, but it took some trial and error and pushing to production. The format that worked was to use the URL of our live site (not GitHub pages URL), as well as the slash at the end:

```
site_url: https://ubcwiki.ca/
```

Here is the last commit: https://github.com/CommunityUBC/ubcwiki/commit/652370ffcb82bf2fc3a4493a1f2cf8882da991db

Hope that works for you as well

**Comment by melwee01** [comment]
Yeah, that looks like ours (which still has the issue):

`site_url: https://<domain>.com/`

We don't publish through GitHub pages at all, only our live site.

Thanks, though. I'll check in with our deployment guys and see what they can dig up.
